num_channels: 3
num_layers: 6
image_size: 32
in_features: 512
patch_size: 3
conv_stride: 3
vq_beta: 0.25
out_features: 512
num_heads: 16
num_latent_tokens: 128
codebook_size: 4096
token_size: 512
dropout: 0.3
enable_reverse_difflin: false
bias: false
enable_cudnn_benchmark: true
enable_cudnn_deterministic: false
config_save_path: config.yaml
